services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq_local
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=my_vhost
